use JSON data for testing generate-actionlint-matcher

diff --git a/.github/workflows/matcher.yaml b/.github/workflows/matcher.yaml
--- a/.github/workflows/matcher.yaml
+++ b/.github/workflows/matcher.yaml
@@ -15,9 +15,15 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
+      - uses: actions/setup-go@v2
+        with:
+          go-version: '1.16'
+      - run: go build ./cmd/actionlint
       - uses: actions/setup-node@v2
         with:
           node-version: "lts/*"
+      - name: Update test data
+        run: make ./scripts/generate-actionlint-matcher/test/*
       - name: Test actionlint-matcher.json
         run: node ./scripts/generate-actionlint-matcher/test.js
       - name: Ensure .github/actionlint-matcher.json is up-to-date
@@ -26,7 +32,7 @@ jobs:
           if git diff --quiet; then
             echo 'OK'
           else
-            echo 'NOT OK'
+            echo 'ERROR! .github/actionlint-matcher.json is outdated. Update it by "make .github/actionlint-matcher.json"' >&2
             set -x
             git diff
             exit 1
